name: Homie
description: "Homie - Find your people. Find your place."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  fl_chart: ^0.69.0
  smooth_page_indicator: ^1.2.0+3
  percent_indicator: ^4.2.4
  shimmer: ^3.0.0
  lottie: ^3.1.2
  url_launcher: ^6.3.1
  timeago: ^3.7.0
  uuid: ^4.5.1
  flutter_animate: ^4.5.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
